pipeline:
  - op: detrending
    method: constant

  - op: detrending
    method: linear

  - op: filtering
    method: iir
    params:
      fmin: 0.0
      fmax: 100_000.0
      order: 4

  - op: slicing
    segment_duration: 0.01
    segment_step: 0.001

  - op: whitening
    method: onebit_apod
    params:
      fmin: 0.0
      fmax: 100_000.0
      taper_width_Hz: 1_000.0

  - op: normalization
    method: onebit

  - op: appodization
    method: hanning
    params:
      frac: 0.1

  - op: correlation
    method: cross
    virtual_source_index: 0
